### ISSUE TITLE
Content is selectable as text

### ISSUE THREAD

**Issue by Cecile-Lebleu** [simonghales/example-react-three-game#1]
First of all, great job! I’m impressed with the fact that this is possible with R3F 👏

This is just a quick improvement I noticed while running the demo on iPad: when holding down to move, the page (or other elements in it, like the moving...circle?) gets selected as if it was text. I think it could be fixed with a quick [user-select: none](https://caniuse.com/user-select-none) but tbh I haven’t dived into the code yet.

**Comment by simonghales** [comment]
Hey thanks for the heads up, I only just saw this now. I had noticed the issue and added `user-select: none` on my private fork already, I just haven't updated this repo in awhile, but am planning to do so once I do some refactoring and make the code a bit neater. But thank you for taking the time to let me know!

edit: decided to push the latest regardless, it should be resolved now :+1:
