### ISSUE TITLE
user-select disabling css to improve mobile UX

### ISSUE THREAD

**Issue by dancrew32** [simonghales/example-react-three-game#2]
Great game setup! Really appreciate you sharing this!

![A42E0C0F-701B-4706-8C4C-A997BB8E1909](https://user-images.githubusercontent.com/86152/103018256-c3f39c80-44f9-11eb-9ab1-fefffd03f2da.jpeg)

I just wanted to recommend adding this user-select disabling css somewhere around the game to prevent touch-hold from activating iOS’ context menu from popping up:
https://stackoverflow.com/a/4407335

**Comment by simonghales** [comment]
Hmm I thought I had fixed this previously but maybe the new UI elements I added reintroduced the issue.

I've pushed a change, could you see if it's resolved for you on https://example-react-three-game.netlify.app/ thanks

**Comment by dancrew32** [comment]
Works great! Thank you!
